[package]
name = "imageToCmdln"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.7"
#math = "0.10.0"
rand = "0.8.0"
